networks:
  logging:

volumes:
  grafana_data: {}
  loki_data: {}
  vector_data: {} # To store read positions for log files

services:
  loki:
    image: grafana/loki:2.9.5 # Pinning version is good practice
    container_name: loki
    # Removed external port exposure
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging
    restart: unless-stopped

  vector:
    image: timberio/vector:0.46.X-alpine # Latest stable version
    container_name: vector
    volumes:
      # Mount the Vector config file
      - ./vector.toml:/etc/vector/vector.toml:ro
      # Mount volume for positions file (needs write access inside container)
      - vector_data:/var/lib/vector
    command: --config /etc/vector/vector.toml
    # Removed external port exposure
    networks:
      - logging
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2 # Pinning version is good practice
    container_name: grafana
    ports:
      - "3000:3000" # Grafana Web UI port
    volumes:
      - grafana_data:/var/lib/grafana
      # Mount provisioning files to auto-configure Loki datasource
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
      # Mount dashboards for version control (read-write)
      - ./dashboards:/etc/grafana/dashboards
    environment:
      # Set admin user/pass (change 'your_strong_password')
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=your_strong_password
      # Skip update checks for local instance
      - GF_UPDATE_CHECKING_ENABLED=false
      # Enable teams provisioning
      - GF_TEAMS_PROVISIONING_ENABLED=true
      # Enable organizations provisioning
      - GF_ORGS_PROVISIONING_ENABLED=true
      # Dashboard settings
      # - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      # - GF_DASHBOARDS_VERSIONS_TO_KEEP=20
      # Optional: allow anonymous access if needed (use with caution)
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - logging
    depends_on:
      - loki
    restart: unless-stopped